name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Build and Upload project
        uses: withastro/action@v1
        with:
          name: dist
          path: dist/
