name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
    - master
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs: [ test ]
    uses: ./.github/workflows/build.yml

  deploy:
      name: Deploy
      if: github.event.pull_request.merged == true
      needs: [ build ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: actions/download-artifact@v3
          with:
            name: dist
            path: dist
            
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: dist
            
